// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnf9gu74fIBaqCbjQmzE7Y3u82zGAsMi8',
    appId: '1:404690523997:web:2465420b491caac4cb3ab4',
    messagingSenderId: '404690523997',
    projectId: 'studybuddy-81789',
    authDomain: 'studybuddy-81789.firebaseapp.com',
    storageBucket: 'studybuddy-81789.firebasestorage.app',
    measurementId: 'G-7YT1HD343E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd-RiJ2iuMDqNbAMbbs2M-H4s3EbJJnyQ',
    appId: '1:404690523997:android:b8e3d05e410a01e3cb3ab4',
    messagingSenderId: '404690523997',
    projectId: 'studybuddy-81789',
    storageBucket: 'studybuddy-81789.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnf9gu74fIBaqCbjQmzE7Y3u82zGAsMi8',
    appId: '1:404690523997:web:e5a768f4bb38b814cb3ab4',
    messagingSenderId: '404690523997',
    projectId: 'studybuddy-81789',
    authDomain: 'studybuddy-81789.firebaseapp.com',
    storageBucket: 'studybuddy-81789.firebasestorage.app',
    measurementId: 'G-KMMH2572D9',
  );

}